version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE # The cap_add set to SYS_NICE suppresses some not useful error messages.
    restart: always
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local